package com.FreshHome.app.repository;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;

import com.FreshHome.app.model.HabilidadesEntity;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: habilidades
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-27
 */
public interface HabilidadesRepository extends MongoRepository<HabilidadesEntity, ObjectId> {
}
