package com.FreshHome.app.repository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;

import com.FreshHome.app.model.SolicitudEntity;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: solicitud
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-27
 */
public interface SolicitudRepository extends MongoRepository<SolicitudEntity, ObjectId> {
	List<SolicitudEntity> findByfechaSolicitudBetween(LocalDateTime entre,LocalDateTime hasta);	
	List<SolicitudEntity> findByIdUsuarioAutor(Integer idUsuarioAutor);
	List<SolicitudEntity> findByIdUsuarioAplicante(Integer idUsuarioAplicante);
}
