package com.FreshHome.app.repository;

import java.util.Optional;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;

import com.FreshHome.app.model.UsuarioEntity;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: usuario
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-04-27
 */
public interface UsuarioRepository extends MongoRepository<UsuarioEntity, ObjectId> {
	Optional<UsuarioRepository> findByidUsuario(int idUsuario);
	void deleteByIdUsuario(int idUsuario);
}
